<?xml version="1.0" encoding="BIG5"?>
<!--		93_8.dtd     公文時效統計     2004.7.1     -->
<!ENTITY  % 基本標籤  SYSTEM "93_基本標籤.ent" >
%基本標籤;
<!ENTITY  % 交換用標籤  SYSTEM "93_交換用標籤.ent" >
%交換用標籤;
<!ELEMENT  公文時效統計		(送達機關,填表機關,填表日期,資料時間,一般公文統計,
立法委員質詢案件統計?,人民申請案件統計?,訴願案件統計?,人民陳情案件統計?,
專案管制案件統計?,機關首長?,單位主管?,填表人?,電話?)>

<!ELEMENT  一般公文統計		(一般_本月新收件數,一般_截至上月待辦件數,
一般_本月創稿數,一般_本月應辦公文總數,一般_六日內辦結,一般_六日內辦結比例,
一般_六至三十日辦結,一般_六至三十日辦結比例,一般_三十日以上辦結,
一般_三十日以上辦結比例,一般_發文件數,一般_存查件數,一般_辦結件數總計,
一般_辦結件數總計比例,一般_發文平均使用日數,一般_待辦件數,一般_待辦件數比例,
一般_未逾辦理期限待辦件數,一般_已逾辦理期限待辦件數)>
<!ELEMENT  立法委員質詢案件統計		(立委_本月新收件數,立委_截至上月待辦件數,
立委_本月應辦件數,立委_依限辦結件數,立委_依限辦結件數比例,立委_逾限辦結件數,
立委_逾限辦結件數比例,立委_逾限五日內辦結件數,立委_逾限五日內辦結件數比例,
立委_逾限五至十日辦結件數,立委_逾限五至十日辦結件數比例,
立委_逾限十至十五日辦結件數,立委_逾限十至十五日辦結件數比例,
立委_逾限十五日以上辦結件數,立委_逾限十五日以上辦結件數比例,
立委_發文平均使用日數,立委_待辦件數,立委_待辦件數比例,
立委_未逾辦理期限待辦件數,立委_已逾辦理期限待辦件數)>
<!ELEMENT  人民申請案件統計	(申請_本月新收件數,申請_截至上月待辦件數,
申請_本月應辦件數,申請_依限辦結件數,申請_依限辦結件數比例,申請_逾限辦結件數,
申請_逾限辦結件數比例,申請_辦結案件總數,申請_辦結案件總數比例,申請_待辦件數,
申請_待辦件數比例,申請_未逾辦理期限待辦件數,申請_已逾辦理期限待辦件數)>
<!ELEMENT  訴願案件統計		(訴願_本月新收件數,訴願_截至上月待辦件數,
訴願_本月應辦件數,訴願_依限辦結件數,訴願_依限辦結件數比例,訴願_逾限辦結件數,
訴願_逾限辦結件數比例,訴願_辦結案件總數,訴願_辦結案件總數比例,訴願_待辦件數,
訴願_待辦件數比例,訴願_未逾辦理期限待辦件數,訴願_已逾辦理期限待辦件數)>
<!ELEMENT  人民陳情案件統計	(陳情_本月新收件數,陳情_截至上月待辦件數,
陳情_本月應辦件數,陳情_依限辦結件數,陳情_依限辦結件數比例,陳情_六日內辦結件數,
陳情_六日內辦結件數比例,陳情_六至十五日辦結件數,陳情_六至十五日辦結件數比例,
陳情_十五至三十日辦結件數,陳情_十五至三十日辦結件數比例,陳情_逾限辦結件數,
陳情_逾限辦結件數比例,陳情_辦結件數,陳情_辦結件數比例,陳情_待辦件數,
陳情_待辦件數比例,陳情_未逾辦理期限待辦件數,陳情_已逾辦理期限待辦件數)>
<!ELEMENT  專案管制案件統計	(專案_本月新增專案數,專案_截至上月待辦專案數,
專案_本月應辦件數,專案_依限辦結件數,專案_逾限辦結件數,專案_已辦結件數,
專案_已辦結件數比例,專案_待辦件數,專案_待辦件數比例,
專案_未逾辦理期限待辦專案數,專案_已逾辦理期限待辦專案數)>
<!-- /公文時效統計 -->
