<?xml version="1.0" encoding="BIG5"?>
<!--	104_ermeta_big5.dtd 電子檔案詮釋資料格式 2015.05.01  -->
<!ENTITY  % 基本標籤  SYSTEM "104_basic_a_big5.ent" >
%基本標籤;
<!ENTITY  % 檔管標籤  SYSTEM "104_records_big5.ent" >
%檔管標籤;
<!ELEMENT ROWSET (案卷)*>
<!ELEMENT 案卷 (案名,並列案名?,其他案名?,檔案產生及管有機關,檔案有關機關?,密等,保存年限,調整後之保存年限?,保存年限調整原因?,年度號,分類號,案次號,	其他編號*,案卷檔案起始日期之年制?,案卷檔案起始日期,案卷檔案迄止日期之年制?,案卷檔案迄止日期,核准銷毀文號?,銷毀日期?,移轉註記?,延長移轉屆滿日期?,移轉日期?,移交日期?,接管機關代碼?,移交機關代碼?,媒體型式*,數量+,計量單位+,外觀細節*,案情摘要+,可參照之有關案卷*,主題,附註*,機關代碼,單位代碼?, 核准使用群*,核准使用者*,應用限制?,應用註記?,複製限制?,應用紀錄*,作業紀錄*,轉置紀錄*,更新紀錄*,備份紀錄*,案件清單)>
<!ELEMENT 案件清單 (案件資訊+)>
<!ELEMENT 案件資訊 (年度號, 分類號, 案次號, 卷次號, 目次號, 檔案路徑, 電子檔案名稱)>
