<?xml version="1.0" encoding="UTF-8"?>
<!--	104_ortransm_utf8.dtd公文檔案管理傳輸格式 2015.05.01  -->
<!ENTITY  % 基本標籤  SYSTEM "104_basic_a_utf8.ent" >
%基本標籤;
<!ENTITY  % 檔管標籤  SYSTEM "104_records_utf8.ent" >
%檔管標籤;
<!ELEMENT ROWSET (案卷|案件)*>
<!ELEMENT 案卷 (系統名稱,功能,案名,並列案名?,其他案名?,檔案產生及管有機關,檔案有關機關?,密等,保存年限,調整後之保存年限?,保存年限調整原因?,應用限制,年度號,分類號,案次號,基準項目編號*,其他編號?,案卷檔案起始日期之年制?,案卷檔案起始日期,案卷檔案迄止日期之年制?,案卷檔案迄止日期,數量+,計量單位+,外觀細節*,案情摘要*,可參照之有關案卷?,主題,附註*,媒體型式*,檔案路徑?,電子檔案名稱*,核准銷毀文號?,銷毀日期?,移轉註記?,延長移轉屆滿日期?,移轉日期?,移交日期?,接管機關代碼?,移交機關代碼?,分類號啟用日期?,史政機關代碼*)>
<!ELEMENT 案件 (系統名稱,功能,案由,並列案由?,其他案由?,有關案件?,主要發文者?,次要發文者*,主要來文者?,次要來文者*,受文者*,文別,本別,密等,解密條件或保密期限?,保存年限,發文字號*,收文字號?,來文字號*,主併文號?,年度號?,分類號,案次號?,卷次號?,目次號?,分類號啟用日期?,正版檔案*,副版檔案*,電子或微縮編號?,其他編號?,文件產生日期之年制?,文件產生日期,來文日期?,發文日期?,媒體型式?,檔案類別,數量+,計量單位+,本文電子檔*,附件紀錄*,附件檔案*,併同歸檔數量? ,外觀細節?,調整後之保存年限?,保存年限調整原因?,史政機關代碼*,核准銷毀文號?,銷毀日期?,解密日期?,移轉註記?,延長移轉屆滿日期?,移轉日期?,移交日期?,接管機關代碼?,移交機關代碼?,保存狀況?,電子檔案處理建議?,浮水印註記?,浮水印?,遮掩註記?,異動人員*,異動日期及時間*,承辦單位,承辦人員,承辦人員職稱,會辦單位*,會辦人員*,會辦人員職稱*,辦畢日期?,送歸日期?,點收日期?,退文日期?,退文原因?,受退單位?)>
