<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="EDR478D" targetNamespace="http://tempuri.org/EDR478D.xsd" elementFormDefault="qualified"
	xmlns="http://tempuri.org/EDR478D.xsd" xmlns:mstns="http://tempuri.org/EDR478D.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Main">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Dept" type="xs:string" />
				<xs:element name="Stander" type="xs:string" />
				<xs:element name="M01" type="xs:string" />
				<xs:element name="M02" type="xs:string" />
				<xs:element name="M03" type="xs:string" />
				<xs:element name="M04" type="xs:string" />
				<xs:element name="M05" type="xs:string" />
				<xs:element name="M06" type="xs:string" />
				<xs:element name="M07" type="xs:string" />
				<xs:element name="M08" type="xs:string" />
				<xs:element name="M09" type="xs:string" />
				<xs:element name="M10" type="xs:string" />
				<xs:element name="M11" type="xs:string" />
				<xs:element name="M12" type="xs:string" />
				<xs:element name="StanderCompare" type="xs:string" />
				<xs:element name="PreviousCompare" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>