<?xml version="1.0"  encoding="BIG5"?>
<!--93_A.dtd     檔案目錄傳輸格式表     2004.7.1 -->
<!ENTITY  % 基本標籤  SYSTEM "93_基本標籤.ent" >
%基本標籤;
<!ENTITY  % 交換用標籤  SYSTEM "93_交換用標籤.ent" >
%交換用標籤;
<!ELEMENT  檔案目錄傳輸格式  (檔案目錄傳送名稱,功能,案由,並列案由?,其它案由?,案名?,相關案件?,主要發文者?,主要來文者?,次要發文者?,次要來文者?,發文者之補正?,來文者之補正?,文別?,本別?,密等,解密條件或保密期限?,保存年限,應用限制?,保存狀況?,調整後之保存年限?,保存年限調整原因?,核准銷毀文號?,銷毀日期?,解密日期?,移轉註記?,延長移轉屆滿日期?,移轉日期?, 發文字號?,收文字號?,來文字號?,年度號,分類號,案次號,卷次號,目次號,電子媒體編號?,電子檔案路徑?,電子檔案名稱*,微縮編號?,文件產生日期,媒體型式?,數量?,計量單位?,附件名稱*,附件媒體型式*,附件數量*,附件單位*,主題*,附註*)+>
<!-- /檔案目錄傳輸格式-->
