<?xml version="1.0" encoding="UTF-8"?>
<!--		99_envelope.dtd     信封表單     2010.01.08    -->
<!ELEMENT	 orgid	(#PCDATA)>
<!ELEMENT 	unitid	(#PCDATA)>
<!ELEMENT	 orgname	(#PCDATA)>
<!ELEMENT 	note	(#PCDATA)>
<!ELEMENT 	serviceid	(#PCDATA)>
<!ELEMENT 	applicationid	(#PCDATA)>
<!ELEMENT 	subject	(#PCDATA)>
<!ELEMENT 	expiredate	(#PCDATA)>
<!ELEMENT 	contactinfo	(#PCDATA)>
<!ELEMENT 	filename	(#PCDATA)>
<!ELEMENT	 hash	(#PCDATA)>
<!ATTLIST	 hash  algorithm	(md5|sha1|sha256|sha384|sha512)  "sha256">
<!ELEMENT 	object	(orgid,unitid,orgname,note?)>
<!ATTLIST 	object  type	(addressbook)  "addressbook">
<!ELEMENT 	senderinfo		(object)>
<!ELEMENT 	receiverlist	(object+)>
<!ELEMENT 	file	(filename,hash,note?)>
<!ATTLIST	file  needsig	(true|false)  "false">
<!ELEMENT 	print	(file)>
<!ELEMENT 	description	(file)>
<!ELEMENT others	(file+)>
<!ELEMENT 	filelist	(print?,description?,others?)>
<!ELEMENT g2b2c-envelope	(senderinfo,receiverlist,serviceid,applicationid?,subject,expiredate?,contactinfo?,filelist?)>
<!-- /g2b2c-envelope -->
