<?xml version="1.0" encoding="BIG5"?>
<!--		 99_recatalog_big5.dtd      檔案目錄彙送格式    2010.10.10   -->
<!ENTITY  % 基本標籤  SYSTEM "99_basic_a_big5.ent" >
%基本標籤;
<!ENTITY  % 檔管標籤  SYSTEM "99_records_big5.ent" >
%檔管標籤;
<!ELEMENT ROWSET (案卷|案件)*>
<!ELEMENT 案卷 (	檔案目錄傳送名稱,功能,案名,並列案名?,其他案名?,檔案產生及管有機關,檔案有關機關?,密等,保存年限,調整後之保存年限?,保存年限調整原因?,應用限制?,應用註記?,複製限制?,媒體型式*,基準項目編號*,年度號,分類號,案次號,其他編號*,案卷檔案起始日期之年制?,案卷檔案起始日期,案卷檔案迄止日期之年制?,案卷檔案迄止日期,數量+,計量單位+,外觀細節*,案情摘要+,可參照之有關案卷*,主題,附註*,核准銷毀文號?,銷毀日期?,移轉註記?,延長移轉屆滿日期?,移轉日期?,移交日期?,接管機關代碼?,移交機關代碼?,分類號啟用日期?,史政機關代碼*)>
<!ELEMENT 案件 (檔案目錄傳送名稱,功能,案由,並列案由?,其他案由?,案名?,有關案件?,主要發文者?,主要來文者?,次要發文者*,次要來文者*,受文者*,文別?,本別?,密等,解密條件或保密期限?,保存年限,保存狀況?,調整後之保存年限?,保存年限調整原因?,核准銷毀文號?,銷毀日期?,解密日期?,移轉註記?,延長移轉屆滿日期?,移轉日期?,移交日期?,接管機關代碼?,移交機關代碼?,發文字號*,收文字號?,來文字號*,年度號,分類號,案次號,卷次號,目次號,電子或微縮編號?,文件產生日期之年制?,文件產生日期,媒體型式?,數量?,計量單位?,附件紀錄*,分類號啟用日期?,史政機關代碼*)>
