<?xml version="1.0" encoding="utf-8"?>
<!ENTITY  % 基本標籤  SYSTEM "94_檔案基本標籤.ent" >
%基本標籤;
<!ENTITY  % 交換用標籤  SYSTEM "94_檔案交換用標籤.ent" >
%交換用標籤;
<!ENTITY  % 內部標籤  SYSTEM "94_檔管內部用標籤.ent" >
%內部標籤;
<!ELEMENT ROWSET (案卷|案件)*>
<!ELEMENT 案卷 (
	案名,相關案名?,機關代碼,單位代碼?,年度號,分類號,
	案次號,卷次號,案卷產生日期,案卷檔案起始日期之年制?,案卷檔案起始日期,
 案卷檔案迄止日期之年制?,案卷檔案迄止日期,移轉日期?,移交日期?,接管機關代碼?,
移交機關代碼?,數量+,計量單位+,異動人員*,異動日期及時間*)>
<!ELEMENT 案件 (
	案由,並列案由?,其他案由?,相關案件?,主要發文者?,主要來文者?,
	受文者*,次要發文者*,次要來文者*,發文者之補正*,來文者之補正*,
	文別?,本別?,發文字號*,收文字號?,來文字號*,機關代碼,單位代碼?,
	年度號,分類號,案次號,卷次號,目次號,電子檔案名稱,
	電子檔案產生日期,電子檔案確認日期,附件紀錄*,
	實體存放位置*,密等,解密條件或保密期限?,
	解密日期?,核准使用群*,核准使用者*,
	保存年限,調整後之保存年限?,保存年限調整原因?,
	核准銷毀文號?,銷毀日期?,移轉註記?,延長移轉屆滿日期?,
     移轉日期?,移交日期?,接管機關代碼?,移交機關代碼?,
     應用限制?,應用註記?,檔案格式*,檔案大小*,檔案格式版本*,編碼方式*,
	電子檔案產生者及修改者*,詮釋資料建立者及修改者*,
	簽核人員*,異動人員*,異動日期及時間*
	)>
